/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    AModal: typeof import('ant-design-vue/es')['Modal']
    APagination: typeof import('ant-design-vue/es')['Pagination']
    ATable: typeof import('ant-design-vue/es')['Table']
    BadgeIcon: typeof import('./src/components/IconCom/BadgeIcon.vue')['default']
    ErrorIcon: typeof import('./src/components/IconCom/ErrorIcon.vue')['default']
    HomeIcon: typeof import('./src/components/IconCom/HomeIcon.vue')['default']
    InfoIcon: typeof import('./src/components/IconCom/InfoIcon.vue')['default']
    LockIcon: typeof import('./src/components/IconCom/LockIcon.vue')['default']
    LoginOutIcon: typeof import('./src/components/IconCom/LoginOutIcon.vue')['default']
    Menu: typeof import('./src/components/com/Menu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VoiceIcon: typeof import('./src/components/IconCom/VoiceIcon.vue')['default']
  }
}
